### ISSUE TITLE
update contributors hof in README

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/scraplink#15]
Generate hof from this site 
https://gh-hof.netlify.com/

**Comment by dasu5** [comment]
Hi, I'd like to work on this as a first timer. You want to generate the hof from that site you mentioned and add it to Read me?

**Comment by dasu5** [comment]
I  started working on this. I did the change but when i run the test as mentioned in the doc "yarn test", i do get errors. Is it the way it should be tested? Could you please help me with that?

**Comment by dasu5** [comment]
The error i get is "Expected linebreaks to be 'LF' but found 'CRLF' linebreak-style" 
In order to solve it, need to add linebreak-style into windows (since I am working in windows) in the .eslintrc.json. Is it okay if I modify that file?

**Comment by arshadkazmi42** [comment]
Can you share the screenshot of errors?
Just to be sure. You need to run following commands
- `npm install`
- `npm test`

Also I just checked the CONTRIBUTING doc states using `yarn` sorry about that, I will get that updated.

You can send a pull request with your changes and we can debug the issue from there if above does not works

**Comment by dasu5** [comment]
<img width="442" alt="error" src="https://user-images.githubusercontent.com/24999223/68829638-59a1e300-06cf-11ea-8d5b-1abcef29d06e.PNG">

**Comment by arshadkazmi42** [comment]
Can you try running this 
`npm run lint -- --fix`

if this does not fix, send a Pull Request. 
I think we will have to configure some eslint to support windows linebreaks.

**Comment by dasu5** [comment]
that error gets for files like index.js, test files, util, scrapper etc. I tried with adding "linebreak-style": ["error", "windows"]" into the .eslintrc.json then it worked. But then when I run npm test, it gives another error 
"> node_modules/mocha/bin/mocha tests/*

'node_modules' is not recognized as an internal or external command,
operable program or batch file."

**Comment by dasu5** [comment]
I just tried this **npm run lint -- --fix** still getting that node_module error

**Comment by arshadkazmi42** [comment]
Ok. just send the pull request. I will check it at my end too. Since this issue is related to only README update, it will not break anything else

**Comment by dasu5** [comment]
yeah okay, I will only keep the change in the README. Removed the modification done to the .eslintrc.json

**Comment by dasu5** [comment]
Getting an not authorized error when push the changes into my branch.

**Comment by dasu5** [comment]
![image](https://user-images.githubusercontent.com/24999223/68830962-1ba6be00-06d3-11ea-8f4d-7ad3d25b76a1.png)


Getting this error when try to push changes to my branch

**Comment by arshadkazmi42** [comment]
you need to push changes to your fork repository and then this repository will show you an option to create pull request

you can change you git config by opening
`.git/config` file in any editor

and change `arshadkazmi42` to your github username `dasu5` and save the file

then try pushing the changes

**Comment by dasu5** [comment]
Thank you @arshadkazmi42 for the help
