### ISSUE TITLE
Fix vulnerability

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/scraplink#21]
- Delete package-lock.json
- Run `npm install`
- Commit package-lock.json
- Create pull request

**Comment by jugalj05hi** [comment]
Hello there, can I take this up? Thanks

**Comment by arshadkazmi42** [comment]
sure. go ahead

**Comment by Jans999** [comment]
Is this still open?

**Comment by arshadkazmi42** [comment]
> Is this still open?

you can take this @jugalj05hi is already working on similar issue in 3 other repositories

**Comment by roshan0708** [comment]
Can I still contribute to the issue? @arshadkazmi42

**Comment by arshadkazmi42** [comment]
@roshan0708 there is already PRs sennt for this.
