### ISSUE TITLE
Remove contributors section from README.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/scraplink#34]

**Comment by venomboss985** [comment]
Hello, I am new to contributing and would like to take this issue.

**Comment by arshadkazmi42** [comment]
@venomboss985 Sure go ahead

**Comment by arshadkazmi42** [comment]
@venomboss985 Please ignore my previous comment. There is already a open PR for this. I missed it I think.

**Comment by venomboss985** [comment]
No worries at all
